terraform-plan:
	cd ../../module/mochi_counter/src && npm run build
	terraform plan

terraform-apply:
	cd ../../module/mochi_counter/src && npm run build
	terraform apply

terraform-apply-auto-approve:
	cd ../../module/mochi_counter/src && npm run build
	terraform apply --auto-approve
